name: Build, Push Docker Image & Update Manifest

on:
  push:
    branches: [ "main" ]

jobs:
  build-push-update:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repo
      uses: actions/checkout@v4

    - name: Log in to Docker Hub
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}

    - name: Build & Push Docker image
      uses: docker/build-push-action@v5
      with:
        context: .
        push: true
        tags: |
          ${{ secrets.DOCKERHUB_USERNAME }}/quotely:latest
          ${{ secrets.DOCKERHUB_USERNAME }}/quotely:${{ github.sha }}

    - name: Update Kubernetes manifest with new image tag
      run: |
        sed -i "s|image: ${{ secrets.DOCKERHUB_USERNAME }}/quotely:.*|image: ${{ secrets.DOCKERHUB_USERNAME }}/quotely:${{ github.sha }}|g" k8s/deployment.yaml

    - name: Commit & Push changes
      run: |
        git config user.name "GitHub Actions"
        git config user.email "actions@github.com"
        git add k8s/deployment.yaml
        git commit -m "Update image tag to ${{ github.sha }}"
        git push
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
